name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    name: Build Docker images for Azure Container Registry and GitHub Container Registry
    environment:
      name: build
    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3

      - name: Build and Deploy
        uses: "./.github/templates/build-deploy"
        with:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          GitHubRegistryUrl: ${{ secrets.GH_REGISTRY_URL }}
          AzureRegistryUrl: ${{ secrets.AZURE_REGISTRY_URL }}
          AzureRegistryUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          AzureRegistryPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          AzureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          AzureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          AzureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AzureWebAppName: httpstatus-prod
          imageName: ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long,prefix=
