name: Build and Deploy to staging

on:
  pull_request:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: httpstatus-preview
  IMAGE_NAME: ${{ github.repository }}

permissions:
  id-token: write
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    name: Build Docker images for Azure Container Registry and GitHub Container Registry
    environment:
      name: build
    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3

      - name: Build and Deploy
        uses: "./.github/templates/build-deploy"
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long,suffix=-preview
